#!/bin/bash

# Get the directory of the current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MODELPATH="$DIR/DeepSpeech-models/deepspeech-0.9.3-models.pbmm"
SCORERPATH="$DIR/DeepSpeech-models/deepspeech-0.9.3-models.scorer"

# Set LD_LIBRARY_PATH to include your custom path, also unset old library path
unset LD_LIBRARY_PATH
#export LD_LIBRARY_PATH="$DIR/app/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/nathan/Documents/RCA-IED/passive-verification-device/app/lib/

# Launch vad_stream, websocket and the Ollama server as concurrent background apps
# $DIR/app/vad_stream --model=$MODELPATH --scorer=$SCORERPATH "$@" & -- old DeepSpeech launch code
python3 $DIR/app/websocketserver.py "$@" &
$DIR/app/llmBridge &
python3 $DIR/app/transcriber.py "$@" &


wait

#clear
#echo "$DIR/app/vad_stream --model=$MODELPATH --scorer=$SCORERPATH "$@""
#echo $LD_LIBRARY_PATH