#!/bin/bash

# Get the directory of the current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MODELPATH="$DIR/DeepSpeech-models/deepspeech-0.9.3-models.pbmm"
SCORERPATH="$DIR/DeepSpeech-models/deepspeech-0.9.3-models.scorer"

# Set LD_LIBRARY_PATH to include your custom path, also unset old library path
unset LD_LIBRARY_PATH
#export LD_LIBRARY_PATH="$DIR/linux_nim_vad_streaming/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/cuda/lib64:/home/nathan/Documents/RCA-IED/passive-verification-device/linux_nim_vad_streaming/lib/

# Launch your Nim application
$DIR/linux_nim_vad_streaming/vad_stream --model=$MODELPATH --scorer=$SCORERPATH "$@"
#clear
#echo "$DIR/linux_nim_vad_streaming/vad_stream --model=$MODELPATH --scorer=$SCORERPATH "$@""
#echo $LD_LIBRARY_PATH