#!/bin/bash

folder_to_watch="./output-voice"
folder_to_send="./output-ai"
script_to_run="./ollama-run"

while true; do
    file=$(inotifywait -e create "$folder_to_watch" | awk '{print $3}')
    
    if [[ "$file" =~ .*\.txt$ ]]; then
        file_path="$folder_to_watch/$file"

        # Check for and remove null bytes from the file
        clean_file_path="/tmp/clean_file.txt"
        tr -d '\000' < "$file_path" > "$clean_file_path"

        file_contents=$(cat "$file_path")

        sanitised_file_contents=$(echo "$file_contents" | tr -cd '[:alnum:] ')

        script_output="$("$script_to_run" "Respond only with one word, "TRUE" or "FALSE": '$file_contents'")"

        output_path="$folder_to_send/$sanitised_file_contents.txt"

        echo "$script_output" | tee -a "$output_path"

        rm -r "$file_path"

        echo "Executed $script_to_run with contents of $file_path ($file_contents) as an argument."
    fi
done
